/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java12_QuaQuaLook;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UnsupportedLookAndFeelException;

/**
 * @author metin
 */
@SuppressWarnings("all")
public class QuaQuaForm extends javax.swing.JFrame {

	/**
	 * Creates new form QuaQuaForm
	 */
	public QuaQuaForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("jButton1");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(66, 66, 66).addComponent(jButton1).addContainerGap(270, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(76, 76, 76).addComponent(jButton1).addContainerGap(196, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *           the command line arguments
	 */
	public static void main(String args[]) {
		try {
			/* Set the Nimbus look and feel */
			// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
			/*
			 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
			 * feel. For details see
			 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
			 */

			javax.swing.UIManager.setLookAndFeel(ch.randelshofer.quaqua.QuaquaManager.getLookAndFeel());

			// </editor-fold>
			/* Create and display the form */
			java.awt.EventQueue.invokeLater(new Runnable() {
				public void run() {
					new QuaQuaForm().setVisible(true);
				}
			});
		} catch (UnsupportedLookAndFeelException ex) {
			Logger.getLogger(QuaQuaForm.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	// End of variables declaration//GEN-END:variables
}
