/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ays.forms;

import com.ays.databaseop.DBConn;
import com.ays.entity.Kisi;

import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**

 @author metin
 */
@SuppressWarnings("all")
public class PanelKisi extends javax.swing.JPanel {

    private ArrayList<String> TCKimlikNo;
    private ArrayList<Kisi> kisiler;

    /**
     Creates new form PanelKisi
     */
    public PanelKisi () {
        initComponents();
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSec = new javax.swing.JLabel();
        cmbAdiSoyadi = new javax.swing.JComboBox();
        lblTCKimlik = new javax.swing.JLabel();
        txtTCKimlik = new javax.swing.JTextField();
        lblAd = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        lblSoyad = new javax.swing.JLabel();
        txtSoyad = new javax.swing.JTextField();
        lblDogumTarih = new javax.swing.JLabel();
        dateDogumTarih = new org.jdesktop.swingx.JXDatePicker();
        lblEmail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblDaireNo = new javax.swing.JLabel();
        cmbDaireNo = new javax.swing.JComboBox();
        lblDurum = new javax.swing.JLabel();
        cmbDurum = new javax.swing.JComboBox();
        btnKaydet = new javax.swing.JButton();
        btnTemizle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();

        lblSec.setText("Sec");

        cmbAdiSoyadi.setModel(getModelAdSoyad());
        cmbAdiSoyadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAdiSoyadiActionPerformed(evt);
            }
        });

        lblTCKimlik.setText("TC Kimlik No");

        lblAd.setText("Adi");

        lblSoyad.setText("Soyadi");

        lblDogumTarih.setText("Dogum Tarihi");

        dateDogumTarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDogumTarihActionPerformed(evt);
            }
        });

        lblEmail.setText("E-posta");

        lblDaireNo.setText("Daire No");

        cmbDaireNo.setModel(getModelDaireNo());

        lblDurum.setText("Durumu");

        cmbDurum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<boş>", "Sahibi", "Kiraci" }));

        btnKaydet.setText("Kaydet");
        btnKaydet.setPreferredSize(new java.awt.Dimension(100, 28));
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnTemizle.setText("Temizle");
        btnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizleActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDaireNo)
                            .addComponent(lblDurum))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDaireNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDurum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTCKimlik)
                            .addComponent(lblAd)
                            .addComponent(lblSoyad)
                            .addComponent(lblDogumTarih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail)
                            .addComponent(lblSec)
                            .addComponent(btnTemizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtemail)
                                    .addComponent(dateDogumTarih, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtSoyad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTCKimlik, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbAdiSoyadi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAdiSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTCKimlik)
                    .addComponent(txtTCKimlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAd)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoyad)
                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDogumTarih)
                    .addComponent(dateDogumTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDaireNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDaireNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDurum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDurum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTemizle)
                    .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSil))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:

        java.util.Date utilDate = dateDogumTarih.getDate(); // dateDogumTarih'ten util.Date alip utilDate isimli nesneyi yaratiyor.
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // utilDate.getTime() metodu ile sqlDate'i yaratip kisi'nin constructor'ina ekleniyor.

        Kisi kisi = new Kisi(TCKimlikNo.get(cmbAdiSoyadi.getSelectedIndex()).toString(), txtTCKimlik.getText(), txtAd.getText(), txtSoyad.getText(), sqlDate, txtemail.getText(), "01", false);

        if (cmbDaireNo.getSelectedIndex() == 0) {

            new DBConn().insertKisi(kisi); // KISI EKLENECEK

        } else if (cmbDaireNo.getSelectedIndex() != 0) {

            new DBConn().updateKisi(kisi); // SADECE KISI GUNCELLENECEK !!! DAIRE GUNCELLEME DE EKLENECEK

        }

        cmbAdiSoyadi.setModel(getModelAdSoyad());

    }//GEN-LAST:event_btnKaydetActionPerformed

    private void dateDogumTarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDogumTarihActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dateDogumTarihActionPerformed

    private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed
        // TODO add your handling code here:
        // Tum alanlari sifirla.
        cmbAdiSoyadi.setSelectedIndex(0);
        txtTCKimlik.setText(null);
        txtAd.setText(null);
        txtSoyad.setText(null);
        dateDogumTarih.setDate(null);
        txtemail.setText(null);
        cmbDaireNo.setSelectedIndex(0);
        cmbDurum.setSelectedIndex(0);
    }//GEN-LAST:event_btnTemizleActionPerformed

    private void cmbAdiSoyadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAdiSoyadiActionPerformed
        // TODO add your handling code here:

        if (cmbAdiSoyadi.getSelectedIndex() > 0) {
            // TC KIMLIK NOSUNA GORE KISIYI VERI TABANINDAN BUL.
            Kisi kisi = new DBConn().getKisi(TCKimlikNo.get(cmbAdiSoyadi.getSelectedIndex()).toString());
            // ALANLARA KISI BILGILARINI YAZDIR.
            txtTCKimlik.setText(kisi.getTCKimlik());
            txtAd.setText(kisi.getAd());
            txtSoyad.setText(kisi.getSoyad());
            dateDogumTarih.setDate(kisi.getDogumTarih());
            txtemail.setText(kisi.getEmail());
            cmbDaireNo.setSelectedItem(kisi.getDaireNo());
            if (kisi.isSahiplik()) {
                cmbDurum.setSelectedItem(1);
            } else if (!kisi.isSahiplik()) {
                cmbDurum.setSelectedIndex(2);
            } else {
                cmbDurum.setSelectedIndex(0);
            }
            //JOptionPane.showMessageDialog(null, TCKimlikNo.get(cmbAdiSoyadi.getSelectedIndex()).toString());

        } else {

            btnTemizleActionPerformed(null); // Eger comboboxta < Yeni > secilmisse alanlari temizle.

        }
    }//GEN-LAST:event_cmbAdiSoyadiActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:

        if (cmbAdiSoyadi.getSelectedIndex() != 0) {

            int onay = JOptionPane.showConfirmDialog(btnSil, "Sectiginiz \"Kisi\"ye ait bilgiler silinecektir!\nEminmisiniz ?", "Silme Onayi", 0, 0);

            if (onay == 0) {

                new DBConn().deleteKisi(new Kisi(TCKimlikNo.get(cmbAdiSoyadi.getSelectedIndex()), "", "", "", null, "", "", true));
                cmbAdiSoyadi.setModel(getModelAdSoyad());
                btnTemizleActionPerformed(null);

            }

        } else {

            MainFrame.durumMesaji("Silmek icin bir kisi secmelisiniz!");

        }
    }//GEN-LAST:event_btnSilActionPerformed

    private DefaultComboBoxModel getModelAdSoyad () {
        if (TCKimlikNo != null) {
            TCKimlikNo.clear();
        } else {
            TCKimlikNo = new ArrayList<String>();
        }
        getTCKimlikNoAll();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("< Yeni >");
        TCKimlikNo.add(" ");
        for (Kisi temp : kisiler) {
            model.addElement(temp.getAd() + " " + temp.getSoyad());
            TCKimlikNo.add(temp.getTCKimlik()); // Combobox'ta ad ve soyad bilgileri eklenirken,burada tckimlik nolari ekleniyor.
        }
        return model;
    }

    private DefaultComboBoxModel getModelDaireNo () {
        // DAIRENO COMBOBOX I DOLDURUYOR
        DefaultComboBoxModel model = new DefaultComboBoxModel(new DBConn().getAllDaire().toArray());
        model.insertElementAt("<bos>", 0);
        return model;
    }

    private void getTCKimlikNoAll () {
        kisiler = new DBConn().getAllKisi();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnTemizle;
    private javax.swing.JComboBox cmbAdiSoyadi;
    private javax.swing.JComboBox cmbDaireNo;
    private javax.swing.JComboBox cmbDurum;
    private org.jdesktop.swingx.JXDatePicker dateDogumTarih;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblDaireNo;
    private javax.swing.JLabel lblDogumTarih;
    private javax.swing.JLabel lblDurum;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSec;
    private javax.swing.JLabel lblSoyad;
    private javax.swing.JLabel lblTCKimlik;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTCKimlik;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
