/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ays.forms;

import javax.swing.JOptionPane;

/**

 @author metin
 */
public class MainFrame extends javax.swing.JFrame {

    public static String durumMesaji = "Heyo!";

    /**
     Creates new form MainFrame
     */
    public MainFrame () {
        initComponents();
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblDurum = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuProgram = new javax.swing.JMenu();
        jmHakkinda = new javax.swing.JMenuItem();
        jmCikis = new javax.swing.JMenuItem();
        menuDaire = new javax.swing.JMenu();
        jmDaireEkle = new javax.swing.JMenuItem();
        jmDaireGuncelle = new javax.swing.JMenuItem();
        menuKisi = new javax.swing.JMenu();
        jmKisiEkle = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apartman Yonetim 1.0");
        setResizable(false);

        lblDurum.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lblDurum.setText(durumMesaji);
        desktopPane.add(lblDurum);
        lblDurum.setBounds(10, 430, 600, 16);
        desktopPane.setLayer(lblDurum, javax.swing.JLayeredPane.DRAG_LAYER);

        menuProgram.setMnemonic('f');
        menuProgram.setText("Program");

        jmHakkinda.setMnemonic('a');
        jmHakkinda.setText("Hakkinda");
        jmHakkinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHakkindaActionPerformed(evt);
            }
        });
        menuProgram.add(jmHakkinda);

        jmCikis.setMnemonic('x');
        jmCikis.setText("Cikis");
        jmCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCikisActionPerformed(evt);
            }
        });
        menuProgram.add(jmCikis);

        menuBar.add(menuProgram);

        menuDaire.setText("Daire");

        jmDaireEkle.setText("Yeni Daire");
        jmDaireEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDaireEkleActionPerformed(evt);
            }
        });
        menuDaire.add(jmDaireEkle);

        jmDaireGuncelle.setText("Daire Guncelle");
        jmDaireGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDaireGuncelleActionPerformed(evt);
            }
        });
        menuDaire.add(jmDaireGuncelle);

        menuBar.add(menuDaire);

        menuKisi.setText("Kisi");

        jmKisiEkle.setText("Kisi Ekle");
        jmKisiEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmKisiEkleActionPerformed(evt);
            }
        });
        menuKisi.add(jmKisiEkle);

        jMenuItem1.setText("Kisi Guncelle");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuKisi.add(jMenuItem1);

        menuBar.add(menuKisi);

        jMenu1.setText("Makbuz");
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmCikisActionPerformed

    private void jmDaireEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDaireEkleActionPerformed
        // TODO add your handling code here:
        JIFrame jifDaire = new JIFrame(260, 360, new PanelDaireEkle(), "Daire Kayit");
        this.desktopPane.add(jifDaire);
    }//GEN-LAST:event_jmDaireEkleActionPerformed

    private void jmDaireGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDaireGuncelleActionPerformed
        // TODO add your handling code here:
        JIFrame jifDaire = new JIFrame(260, 360, new PanelDaireGuncelle(), "Daire Guncelle");
        this.desktopPane.add(jifDaire);
    }//GEN-LAST:event_jmDaireGuncelleActionPerformed

    private void jmHakkindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHakkindaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, this.getTitle());
    }//GEN-LAST:event_jmHakkindaActionPerformed

    private void jmKisiEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmKisiEkleActionPerformed
        // TODO add your handling code here:
        JIFrame jifDaire = new JIFrame(260, 210, new PanelKisiEkle(), "Kisi Ekle");
        this.desktopPane.add(jifDaire);
    }//GEN-LAST:event_jmKisiEkleActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JIFrame jifDaire = new JIFrame(300, 240, new PanelKisiGuncelle(), "Kisi Bilgi Guncelle");
        this.desktopPane.add(jifDaire);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public static void durumMesaji (String mesaj) {
        lblDurum.setText(mesaj);
    }

    /**
     @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run () {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmCikis;
    private javax.swing.JMenuItem jmDaireEkle;
    private javax.swing.JMenuItem jmDaireGuncelle;
    private javax.swing.JMenuItem jmHakkinda;
    private javax.swing.JMenuItem jmKisiEkle;
    public static javax.swing.JLabel lblDurum;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDaire;
    private javax.swing.JMenu menuKisi;
    private javax.swing.JMenu menuProgram;
    // End of variables declaration//GEN-END:variables

}
