/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ays.forms;

import com.ays.databaseop.DBCommit;
import com.ays.databaseop.DBConn;
import com.ays.entity.Daire;
import com.ays.entity.Kisi;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**

 @author metin
 */
public class PanelKisi extends javax.swing.JPanel {

    /**
     Creates new form PanelKisi
     */
    public PanelKisi () {
        initComponents();
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSec = new javax.swing.JLabel();
        cmbKisiBilgileri = new javax.swing.JComboBox();
        lblTCKimlik = new javax.swing.JLabel();
        txtTCKimlik = new javax.swing.JTextField();
        lblAd = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        lblSoyad = new javax.swing.JLabel();
        txtSoyad = new javax.swing.JTextField();
        lblDogumTarih = new javax.swing.JLabel();
        dateDogumTarih = new org.jdesktop.swingx.JXDatePicker();
        btnKaydet = new javax.swing.JButton();
        btnTemizle = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblDaireNo = new javax.swing.JLabel();
        cmbDaireNo = new javax.swing.JComboBox();
        lblDurum = new javax.swing.JLabel();
        cmbDurum = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        lblSec.setText("Sec");

        cmbKisiBilgileri.setModel(cmbKisiListesiDoldur());

        lblTCKimlik.setText("TC Kimlik No");

        lblAd.setText("Adi");

        lblSoyad.setText("Soyadi");

        lblDogumTarih.setText("Dogum Tarihi");

        dateDogumTarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDogumTarihActionPerformed(evt);
            }
        });

        btnKaydet.setText("Kaydet");
        btnKaydet.setPreferredSize(new java.awt.Dimension(100, 28));
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnTemizle.setText("Temizle");
        btnTemizle.setPreferredSize(new java.awt.Dimension(59, 28));
        btnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizleActionPerformed(evt);
            }
        });

        lblEmail.setText("E-posta");

        lblDaireNo.setText("Daire No");

        cmbDaireNo.setModel(cmbDaireNoDoldur());

        lblDurum.setText("Durumu");

        cmbDurum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<boş>", "Sahibi", "Kiraci" }));

        jButton1.setText("Sil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDaireNo)
                            .addComponent(lblDurum))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDaireNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDurum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTCKimlik)
                            .addComponent(lblAd)
                            .addComponent(lblSoyad)
                            .addComponent(lblDogumTarih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail)
                            .addComponent(lblSec)
                            .addComponent(btnTemizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtemail)
                                    .addComponent(dateDogumTarih, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoyad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTCKimlik, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbKisiBilgileri, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKisiBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTCKimlik)
                    .addComponent(txtTCKimlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAd)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoyad)
                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDogumTarih)
                    .addComponent(dateDogumTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDaireNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDaireNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDurum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDurum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:
        java.util.Date utilDate = dateDogumTarih.getDate(); // dateDogumTarih'ten util.Date alip util.Date yaratiyor.
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // utilDate.getTime() ile sql.Date yaratip Kisi'nin constructor'ina veriyor
        Kisi kisi = new Kisi(txtTCKimlik.getText(), txtAd.getText(), txtSoyad.getText(), sqlDate, txtemail.getText());
        DBCommit connection = new DBCommit();
        int sonuc = connection.insertKisiDaire(kisi, cmbDaireNo.getSelectedItem().toString(), cmbDurum.getSelectedItem().toString().equals("Sahibi"));
        MainFrame.durumMesaji((sonuc == 1 ? "Kisi kayidi olusturuldu" : "Kisi kayidi basarisiz!"));
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void dateDogumTarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDogumTarihActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dateDogumTarihActionPerformed

    private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed
        // TODO add your handling code here:
        txtTCKimlik.setText(null);
        txtAd.setText(null);
        txtSoyad.setText(null);
        dateDogumTarih.setDate(null);
        txtemail.setText(null);
        cmbDaireNo.setSelectedIndex(0);
        cmbDurum.setSelectedIndex(0);
    }//GEN-LAST:event_btnTemizleActionPerformed

    public DefaultComboBoxModel cmbKisiListesiDoldur () {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ArrayList<Kisi> kisiler = new DBConn().getAllKisi();
        model.addElement("< Yeni >");
        for (Kisi temp : kisiler) {
            model.addElement(temp.getAd() + " " + temp.getSoyad());
        }
        return model;
    }

    public DefaultComboBoxModel cmbDaireNoDoldur () {
        // DAIRENO COMBOBOX I DOLDURUYOR
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ArrayList<Daire> daireler = new DBConn().getAllDaire();
        model.addElement("<bos>".toString());
        for (Daire d : daireler) {
            model.addElement(d.getDaireNo().toString());
        }
        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnTemizle;
    private javax.swing.JComboBox cmbDaireNo;
    private javax.swing.JComboBox cmbDurum;
    private javax.swing.JComboBox cmbKisiBilgileri;
    private org.jdesktop.swingx.JXDatePicker dateDogumTarih;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblDaireNo;
    private javax.swing.JLabel lblDogumTarih;
    private javax.swing.JLabel lblDurum;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSec;
    private javax.swing.JLabel lblSoyad;
    private javax.swing.JLabel lblTCKimlik;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTCKimlik;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
