/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ays.z_unused;

import com.ays.databaseop.DBConn;
import com.ays.entity.Daire;
import com.ays.forms.MainFrame;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**

 @author metin
 */
public class PanelDaireGuncelle extends javax.swing.JPanel {

    /**
     Creates new form panelDaire
     */
    public PanelDaireGuncelle () {
        initComponents();
        cmbDaireNo.setModel(comboBoxDoldur()); // COMBOBOX IN ICINI DOLDURUYOR
        cmbDaireNoActionPerformed(null); // pencere acildiginda checkbox a daire numaralarini getir.
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDaireNo = new javax.swing.JLabel();
        cmbDaireNo = new javax.swing.JComboBox();
        lblMetreKare = new javax.swing.JLabel();
        txtMetreKare = new javax.swing.JTextField();
        lblOdaSayisi = new javax.swing.JLabel();
        txtOdaSayisi = new javax.swing.JTextField();
        lblKatNo = new javax.swing.JLabel();
        txtKatNo = new javax.swing.JTextField();
        lblCephe = new javax.swing.JLabel();
        txtCephe = new javax.swing.JTextField();
        lblEbeveynBanyo = new javax.swing.JLabel();
        ckbEbeveynBanyo = new javax.swing.JCheckBox();
        lblBalkonSayisi = new javax.swing.JLabel();
        txtBalkonSayisi = new javax.swing.JTextField();
        lblbDublex = new javax.swing.JLabel();
        ckbDublex = new javax.swing.JCheckBox();
        btnSil = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();

        lblDaireNo.setText("Daire No");

        cmbDaireNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDaireNoActionPerformed(evt);
            }
        });

        lblMetreKare.setText("Metre Kare");

        lblOdaSayisi.setText("Oda Sayisi");

        lblKatNo.setText("Kat No");

        lblCephe.setText("Cephe");

        lblEbeveynBanyo.setText("Ebeveyn Banyo");

        ckbEbeveynBanyo.setText("= Var/Yok");

        lblBalkonSayisi.setText("Balkon Sayisi");

        lblbDublex.setText("Dublex");

        ckbDublex.setText("= Evet/Hayır");

        btnSil.setText("Sil");

        btnGuncelle.setText("Guncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetreKare)
                    .addComponent(lblDaireNo)
                    .addComponent(lblOdaSayisi)
                    .addComponent(lblKatNo)
                    .addComponent(lblCephe)
                    .addComponent(lblEbeveynBanyo)
                    .addComponent(lblbDublex)
                    .addComponent(lblBalkonSayisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMetreKare, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtOdaSayisi, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtKatNo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtCephe, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtBalkonSayisi, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(ckbDublex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbEbeveynBanyo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDaireNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDaireNo)
                    .addComponent(cmbDaireNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetreKare)
                    .addComponent(txtMetreKare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKatNo)
                    .addComponent(txtKatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCephe)
                    .addComponent(txtCephe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOdaSayisi)
                    .addComponent(txtOdaSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEbeveynBanyo)
                    .addComponent(ckbEbeveynBanyo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalkonSayisi)
                    .addComponent(txtBalkonSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbDublex)
                    .addComponent(ckbDublex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSil)
                    .addComponent(btnGuncelle))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private DefaultComboBoxModel comboBoxDoldur () {
        // Bu metod PanelDaireGuncelle.java ekranindaki cmbDaireNo'nun icini doldurmak icindir.
        DBConn baglanti = new DBConn();
        DefaultComboBoxModel cmbxModel = new DefaultComboBoxModel();
        ArrayList<Daire> daireler = baglanti.getAllDaire();
        for (Daire d : daireler) {
            cmbxModel.addElement(d.getDaireNo());
        }
        return cmbxModel;
    }

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        // TODO add your handling code here:
        DBConn connection = new DBConn();
        Daire daire = new Daire(cmbDaireNo.getSelectedItem().toString(), Integer.parseInt(txtMetreKare.getText()), Integer.parseInt(txtKatNo.getText()), txtCephe.getText(), txtOdaSayisi.getText(), ckbEbeveynBanyo.isSelected(), Integer.parseInt(txtBalkonSayisi.getText()), ckbDublex.isSelected());
        int durum = connection.updateDaire(daire);
        MainFrame.durumMesaji(((durum == 1) ? "Kayit guncellendi." : "Kayit guncelleme basarisiz!"));
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void cmbDaireNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDaireNoActionPerformed
        // TODO add your handling code here:
        /**
         checkbox tan daire no secildiginde alt taraftaki alanlara secilen dairenin
         bilgileri getirilecek
         */
        Daire daire = new DBConn().getDaire(cmbDaireNo.getSelectedItem().toString());
        txtMetreKare.setText(String.valueOf(daire.getMetreKare()));
        txtKatNo.setText(String.valueOf(daire.getKatNo()));
        txtCephe.setText(daire.getCephe());
        txtOdaSayisi.setText(daire.getOdaSayisi());
        ckbEbeveynBanyo.setSelected(daire.isEbeveynBanyo());
        txtBalkonSayisi.setText(String.valueOf(daire.getBalkonSayisi()));
        ckbDublex.setSelected(daire.isDublex());
    }//GEN-LAST:event_cmbDaireNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnSil;
    private javax.swing.JCheckBox ckbDublex;
    private javax.swing.JCheckBox ckbEbeveynBanyo;
    private javax.swing.JComboBox cmbDaireNo;
    private javax.swing.JLabel lblBalkonSayisi;
    private javax.swing.JLabel lblCephe;
    private javax.swing.JLabel lblDaireNo;
    private javax.swing.JLabel lblEbeveynBanyo;
    private javax.swing.JLabel lblKatNo;
    private javax.swing.JLabel lblMetreKare;
    private javax.swing.JLabel lblOdaSayisi;
    private javax.swing.JLabel lblbDublex;
    private javax.swing.JTextField txtBalkonSayisi;
    private javax.swing.JTextField txtCephe;
    private javax.swing.JTextField txtKatNo;
    private javax.swing.JTextField txtMetreKare;
    private javax.swing.JTextField txtOdaSayisi;
    // End of variables declaration//GEN-END:variables
}
