/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ays.z_unused;

import com.ays.databaseop.DBConn;
import com.ays.entity.Daire;
import com.ays.entity.Kisi;
import com.ays.forms.MainFrame;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**

 @author metin
 */
public class PanelKisiEkle extends javax.swing.JPanel {

    /**
     Creates new form PanelKisi
     */
    public PanelKisiEkle () {
        initComponents();

    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTCKimlik = new javax.swing.JLabel();
        txtTCKimlik = new javax.swing.JTextField();
        lblAd = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        lblSoyad = new javax.swing.JLabel();
        txtSoyad = new javax.swing.JTextField();
        lblDogumTarih = new javax.swing.JLabel();
        dateDogumTarih = new org.jdesktop.swingx.JXDatePicker();
        btnKaydet = new javax.swing.JButton();
        btnTemizle = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();

        lblTCKimlik.setText("TC Kimlik No");

        lblAd.setText("Adi");

        lblSoyad.setText("Soyadi");

        lblDogumTarih.setText("Dogum Tarihi");

        dateDogumTarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDogumTarihActionPerformed(evt);
            }
        });

        btnKaydet.setText("Kaydet");
        btnKaydet.setPreferredSize(new java.awt.Dimension(100, 28));
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnTemizle.setText("Formu Temizle");

        lblEmail.setText("E-posta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTemizle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTCKimlik)
                            .addComponent(lblAd)
                            .addComponent(lblSoyad)
                            .addComponent(lblDogumTarih)
                            .addComponent(lblEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAd, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtTCKimlik, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(dateDogumTarih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTCKimlik)
                    .addComponent(txtTCKimlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAd)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoyad)
                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDogumTarih)
                    .addComponent(dateDogumTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTemizle)
                    .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:
        java.util.Date utilDate = dateDogumTarih.getDate(); // dateDogumTarih'ten util.Date alip util.Date yaratiyor.
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // utilDate.getTime() ile sql.Date yaratip Kisi'nin constructor'ina veriyor
        Kisi kisi = new Kisi(txtTCKimlik.getText(), txtAd.getText(), txtSoyad.getText(), sqlDate, txtemail.getText());
        DBConn connection = new DBConn();
        int sonuc = connection.insertKisi(kisi);
        MainFrame.durumMesaji((sonuc == 1 ? "Kisi kayidi olusturuldu" : "Kisi kayidi basarisiz!"));
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void dateDogumTarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDogumTarihActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dateDogumTarihActionPerformed

    private DefaultComboBoxModel comboBoxDoldur (DBConn baglanti) {
        // Bu metod PanelKisiEkle.java ekranindaki cmbDaireNo'nun icini doldurmak icindir.
        DefaultComboBoxModel cmbxModel = new DefaultComboBoxModel();
        ArrayList<Daire> daireler = baglanti.getAllDaire();
        cmbxModel.addElement(new String("Bos"));
        for (Daire d : daireler) {
            cmbxModel.addElement(d.getDaireNo());
        }
        return cmbxModel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnTemizle;
    private org.jdesktop.swingx.JXDatePicker dateDogumTarih;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblDogumTarih;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSoyad;
    private javax.swing.JLabel lblTCKimlik;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTCKimlik;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
