/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ays.z_unused;

import com.ays.databaseop.DBConn;
import com.ays.entity.Daire;
import com.ays.forms.MainFrame;

/**

 @author metin
 */
public class PanelDaireEkle extends javax.swing.JPanel {

    /**
     Creates new form panelDaire
     */
    public PanelDaireEkle () {
        initComponents();
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDaireNo = new javax.swing.JLabel();
        txtDaireNo = new javax.swing.JTextField();
        lblMetreKare = new javax.swing.JLabel();
        txtMetreKare = new javax.swing.JTextField();
        lblOdaSayisi = new javax.swing.JLabel();
        txtOdaSayisi = new javax.swing.JTextField();
        lblKatNo = new javax.swing.JLabel();
        txtKatNo = new javax.swing.JTextField();
        lblCephe = new javax.swing.JLabel();
        txtCephe = new javax.swing.JTextField();
        lblEbeveynBanyo = new javax.swing.JLabel();
        ckbEbeveynBanyo = new javax.swing.JCheckBox();
        lblBalkonSayisi = new javax.swing.JLabel();
        txtBalkonSayisi = new javax.swing.JTextField();
        lblbDublex = new javax.swing.JLabel();
        ckbDublex = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        lblDaireNo.setText("Daire No");

        lblMetreKare.setText("Metre Kare");

        lblOdaSayisi.setText("Oda Sayisi");

        lblKatNo.setText("Kat No");

        lblCephe.setText("Cephe");

        lblEbeveynBanyo.setText("Ebeveyn Banyo");

        lblBalkonSayisi.setText("Balkon Sayisi");

        lblbDublex.setText("Dublex");

        jButton1.setText("Temizle");

        jButton2.setText("Kaydet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetreKare)
                    .addComponent(lblDaireNo)
                    .addComponent(lblOdaSayisi)
                    .addComponent(lblKatNo)
                    .addComponent(lblCephe)
                    .addComponent(lblEbeveynBanyo)
                    .addComponent(lblbDublex)
                    .addComponent(lblBalkonSayisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDaireNo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtMetreKare, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtOdaSayisi, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtKatNo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtCephe, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtBalkonSayisi, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(ckbDublex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbEbeveynBanyo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDaireNo)
                    .addComponent(txtDaireNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetreKare)
                    .addComponent(txtMetreKare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKatNo)
                    .addComponent(txtKatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCephe)
                    .addComponent(txtCephe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOdaSayisi)
                    .addComponent(txtOdaSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEbeveynBanyo)
                    .addComponent(ckbEbeveynBanyo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalkonSayisi)
                    .addComponent(txtBalkonSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbDublex)
                    .addComponent(ckbDublex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DBConn connection = new DBConn();
        Daire daire = new Daire(txtDaireNo.getText(), Integer.parseInt(txtMetreKare.getText()), Integer.parseInt(txtKatNo.getText()), txtCephe.getText(), txtOdaSayisi.getText(), ckbEbeveynBanyo.isSelected(), Integer.parseInt(txtBalkonSayisi.getText()), ckbDublex.isSelected());
        int durum = connection.insertDaire(daire);
        MainFrame.durumMesaji(((durum == 1) ? "Kayit olusturuldu." : "Kayit basarisiz!"));
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbDublex;
    private javax.swing.JCheckBox ckbEbeveynBanyo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblBalkonSayisi;
    private javax.swing.JLabel lblCephe;
    private javax.swing.JLabel lblDaireNo;
    private javax.swing.JLabel lblEbeveynBanyo;
    private javax.swing.JLabel lblKatNo;
    private javax.swing.JLabel lblMetreKare;
    private javax.swing.JLabel lblOdaSayisi;
    private javax.swing.JLabel lblbDublex;
    private javax.swing.JTextField txtBalkonSayisi;
    private javax.swing.JTextField txtCephe;
    private javax.swing.JTextField txtDaireNo;
    private javax.swing.JTextField txtKatNo;
    private javax.swing.JTextField txtMetreKare;
    private javax.swing.JTextField txtOdaSayisi;
    // End of variables declaration//GEN-END:variables
}
