package hibernateweb;
// Generated 25.Haz.2014 09:48:40 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 Certificate generated by hbm2java
 */
public class Certificate implements java.io.Serializable {

    private int id;
    private String certificateName;
    private Set employees = new HashSet(0);

    public Certificate () {
    }

    public Certificate (int id) {
        this.id = id;
    }

    public Certificate (String certificateName) {
        this.certificateName = certificateName;
    }

    public Certificate (int id, String certificateName, Set employees) {
        this.id = id;
        this.certificateName = certificateName;
        this.employees = employees;
    }

    public int getId () {
        return this.id;
    }

    public void setId (int id) {
        this.id = id;
    }

    public String getCertificateName () {
        return this.certificateName;
    }

    public void setCertificateName (String certificateName) {
        this.certificateName = certificateName;
    }

    public Set getEmployees () {
        return this.employees;
    }

    public void setEmployees (Set employees) {
        this.employees = employees;
    }

    public String getName () {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
