package hibernateweb;
// Generated 25.Haz.2014 09:48:40 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

    private int id;
    private String firstName;
    private String lastName;
    private Integer salary;
    private Set certificates = new HashSet(0);

    public Employee () {
    }

    public Employee (int id) {
        this.id = id;
    }

    public Employee (String firstName, String lastName, Integer salary) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.salary = salary;
    }

    public Employee (int id, String firstName, String lastName, Integer salary, Set cert) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.salary = salary;
        this.certificates = cert;
    }

    public int getId () {
        return this.id;
    }

    public void setId (int id) {
        this.id = id;
    }

    public String getFirstName () {
        return this.firstName;
    }

    public void setFirstName (String firstName) {
        this.firstName = firstName;
    }

    public String getLastName () {
        return this.lastName;
    }

    public void setLastName (String lastName) {
        this.lastName = lastName;
    }

    public Integer getSalary () {
        return this.salary;
    }

    public void setSalary (Integer salary) {
        this.salary = salary;
    }

    public Set getCertıfıcates () {
        return this.certificates;
    }

    public void setCertıfıcates (Set certıfıcates) {
        this.certificates = certıfıcates;
    }

    public void setCertificates (Set cert) {
        this.certificates = cert;
    }

    public Set getCertificates () {
        return this.certificates;
    }

}
