package temp02_abstract;

public abstract class Canli {

	private String ad;

	public abstract void yuru();

	public String getAd() {
		return ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	/**
	 * ABSTRACT SINIFLARIN KENDISINDEN NESNE YARATILAMAZ. <br>
	 * FAKAT ABSTRACT SINIFTAN TUREYEN ALT SINIFLARDAN YARATILAN NESNELER, ABSTRACT SINIFIN TURUNDE
	 * TANIMLANMIS BASKA BIR DEGISKENI REFERANS DEGISKENI OLARAK KULLANABILIRLER. <br>
	 * BU DURUMDA SUPERCLASS TA OLMAYAN SUBCLASS OZELLIKLERI DEVREDISI KALIR.<BR>
	 * ABSTRACT SINIFTAN TUREMIS SINIFLARA SOMUT SINIF (CONCRETE CLASS) DENIR.
	 */
}
