package com.wissen.entity;
// Generated 24.Haz.2014 21:54:41 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * TblDaire generated by hbm2java
 */
public class TblDaire  implements java.io.Serializable {


     private Serializable daireNo;
     private Integer metreKare;
     private Integer katNo;
     private Serializable cephe;
     private Serializable odaSayisi;
     private Boolean ebeveynBanyo;
     private Integer balkonSayisi;
     private Boolean dublex;
     private Set tblKisiDaires = new HashSet(0);

    public TblDaire() {
    }

	
    public TblDaire(Serializable daireNo) {
        this.daireNo = daireNo;
    }
    public TblDaire(Serializable daireNo, Integer metreKare, Integer katNo, Serializable cephe, Serializable odaSayisi, Boolean ebeveynBanyo, Integer balkonSayisi, Boolean dublex, Set tblKisiDaires) {
       this.daireNo = daireNo;
       this.metreKare = metreKare;
       this.katNo = katNo;
       this.cephe = cephe;
       this.odaSayisi = odaSayisi;
       this.ebeveynBanyo = ebeveynBanyo;
       this.balkonSayisi = balkonSayisi;
       this.dublex = dublex;
       this.tblKisiDaires = tblKisiDaires;
    }
   
    public Serializable getDaireNo() {
        return this.daireNo;
    }
    
    public void setDaireNo(Serializable daireNo) {
        this.daireNo = daireNo;
    }
    public Integer getMetreKare() {
        return this.metreKare;
    }
    
    public void setMetreKare(Integer metreKare) {
        this.metreKare = metreKare;
    }
    public Integer getKatNo() {
        return this.katNo;
    }
    
    public void setKatNo(Integer katNo) {
        this.katNo = katNo;
    }
    public Serializable getCephe() {
        return this.cephe;
    }
    
    public void setCephe(Serializable cephe) {
        this.cephe = cephe;
    }
    public Serializable getOdaSayisi() {
        return this.odaSayisi;
    }
    
    public void setOdaSayisi(Serializable odaSayisi) {
        this.odaSayisi = odaSayisi;
    }
    public Boolean getEbeveynBanyo() {
        return this.ebeveynBanyo;
    }
    
    public void setEbeveynBanyo(Boolean ebeveynBanyo) {
        this.ebeveynBanyo = ebeveynBanyo;
    }
    public Integer getBalkonSayisi() {
        return this.balkonSayisi;
    }
    
    public void setBalkonSayisi(Integer balkonSayisi) {
        this.balkonSayisi = balkonSayisi;
    }
    public Boolean getDublex() {
        return this.dublex;
    }
    
    public void setDublex(Boolean dublex) {
        this.dublex = dublex;
    }
    public Set getTblKisiDaires() {
        return this.tblKisiDaires;
    }
    
    public void setTblKisiDaires(Set tblKisiDaires) {
        this.tblKisiDaires = tblKisiDaires;
    }




}


