package com.wissen.entity;
// Generated 24.Haz.2014 21:54:41 by Hibernate Tools 3.6.0



/**
 * TblKisiDaire generated by hbm2java
 */
public class TblKisiDaire  implements java.io.Serializable {


     private TblKisiDaireId id;
     private TblKisi tblKisi;
     private TblDaire tblDaire;

    public TblKisiDaire() {
    }

    public TblKisiDaire(TblKisiDaireId id, TblKisi tblKisi, TblDaire tblDaire) {
       this.id = id;
       this.tblKisi = tblKisi;
       this.tblDaire = tblDaire;
    }
   
    public TblKisiDaireId getId() {
        return this.id;
    }
    
    public void setId(TblKisiDaireId id) {
        this.id = id;
    }
    public TblKisi getTblKisi() {
        return this.tblKisi;
    }
    
    public void setTblKisi(TblKisi tblKisi) {
        this.tblKisi = tblKisi;
    }
    public TblDaire getTblDaire() {
        return this.tblDaire;
    }
    
    public void setTblDaire(TblDaire tblDaire) {
        this.tblDaire = tblDaire;
    }




}


