package com.wissen.entity;
// Generated 24.Haz.2014 21:54:41 by Hibernate Tools 3.6.0



/**
 * TblKisiDaireId generated by hbm2java
 */
public class TblKisiDaireId  implements java.io.Serializable {


     private byte[] tckimlikNo;
     private byte[] daireNo;
     private boolean sahiplikDurumu;

    public TblKisiDaireId() {
    }

    public TblKisiDaireId(byte[] tckimlikNo, byte[] daireNo, boolean sahiplikDurumu) {
       this.tckimlikNo = tckimlikNo;
       this.daireNo = daireNo;
       this.sahiplikDurumu = sahiplikDurumu;
    }
   
    public byte[] getTckimlikNo() {
        return this.tckimlikNo;
    }
    
    public void setTckimlikNo(byte[] tckimlikNo) {
        this.tckimlikNo = tckimlikNo;
    }
    public byte[] getDaireNo() {
        return this.daireNo;
    }
    
    public void setDaireNo(byte[] daireNo) {
        this.daireNo = daireNo;
    }
    public boolean isSahiplikDurumu() {
        return this.sahiplikDurumu;
    }
    
    public void setSahiplikDurumu(boolean sahiplikDurumu) {
        this.sahiplikDurumu = sahiplikDurumu;
    }




}


