package com.wissen.entity;
// Generated 24.Haz.2014 21:54:41 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblKisi generated by hbm2java
 */
public class TblKisi  implements java.io.Serializable {


     private Serializable tckimlikNo;
     private Serializable adi;
     private Serializable soyadi;
     private Date dogumTarihi;
     private Serializable email;
     private Set tblKisiDaires = new HashSet(0);

    public TblKisi() {
    }

	
    public TblKisi(Serializable tckimlikNo) {
        this.tckimlikNo = tckimlikNo;
    }
    public TblKisi(Serializable tckimlikNo, Serializable adi, Serializable soyadi, Date dogumTarihi, Serializable email, Set tblKisiDaires) {
       this.tckimlikNo = tckimlikNo;
       this.adi = adi;
       this.soyadi = soyadi;
       this.dogumTarihi = dogumTarihi;
       this.email = email;
       this.tblKisiDaires = tblKisiDaires;
    }
   
    public Serializable getTckimlikNo() {
        return this.tckimlikNo;
    }
    
    public void setTckimlikNo(Serializable tckimlikNo) {
        this.tckimlikNo = tckimlikNo;
    }
    public Serializable getAdi() {
        return this.adi;
    }
    
    public void setAdi(Serializable adi) {
        this.adi = adi;
    }
    public Serializable getSoyadi() {
        return this.soyadi;
    }
    
    public void setSoyadi(Serializable soyadi) {
        this.soyadi = soyadi;
    }
    public Date getDogumTarihi() {
        return this.dogumTarihi;
    }
    
    public void setDogumTarihi(Date dogumTarihi) {
        this.dogumTarihi = dogumTarihi;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Set getTblKisiDaires() {
        return this.tblKisiDaires;
    }
    
    public void setTblKisiDaires(Set tblKisiDaires) {
        this.tblKisiDaires = tblKisiDaires;
    }




}


